name: Check new patch
permissions: write-all
on:
  schedule:
    - cron: "0 9 * * *"
  workflow_dispatch:
    inputs:
      retry_count:
        description: 'Do not change value below'
        required: false
        default: '1'
jobs:
  check:
    name: Check new patch
    runs-on: ubuntu-latest
    env:
      repository: ${{ github.repository }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4.1.1
      - name: Check github connection
        id: check-gh
        run: bash src/etc/connection.sh
      - name: Check new patch Revanced Extended
        id: check-rve
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh inotia00/revanced-patches latest youtube-revanced-extended.apk
      - name: Check new patch Revanced Extended Beta
        id: check-rve-beta
        if: steps.check-gh.outputs.internet_error == '0'
        run: bash src/etc/ci.sh inotia00/revanced-patches prerelease youtube-beta-revanced-extended.apk
      - name: Keep workflow run
        if: steps.check-gh.outputs.internet_error == '0'
        uses: gautamkrishnar/keepalive-workflow@v1
      - name: Re-run workflow if github connection not stable
        if: always() && steps.check-rv.outcome == 'skipped' && env.retry_count < env.max_retries
        uses: actions/github-script@v7
        with:
          script: |
            const maxRetries = ${{ env.max_retries }};
            let retryCount = ${{ env.retry_count }};
            if (retryCount < maxRetries) {
              retryCount += 1;
              await github.rest.actions.createWorkflowDispatch({
                owner: context.repo.owner,
                repo: context.repo.repo,
                workflow_id: "ci.yml",
                ref: context.ref,
                inputs: {
                  'retry_count': String(retryCount)
                }
              });
            }
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          retry_count: ${{ github.event.inputs.retry_count }}
          max_retries: 3
    outputs:
      check_rve: ${{ steps.check-rve.outputs.new_patch }}
      check_rve_beta: ${{ steps.check-rve-beta.outputs.new_patch }}

  Patch-Revanced-Extended:
    name: Patch Revanced Extended
    needs: check
    if: ${{ needs.check.outputs.check_rve == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended"
  Patch-Revanced-Extended-Beta:
    name: Patch Revanced Extended Beta
    needs: check
    if: ${{ needs.check.outputs.check_rve_beta == 1 }}
    uses: ./.github/workflows/manual-patch.yml
    with:
      org: "Revanced Extended Beta"