name: Manual Patch
permissions: write-all
env:
  repository: ${{ github.repository }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  org_input: ${{ inputs.org }}
  org_event_input: ${{ github.event.inputs.org }}
on:
  workflow_dispatch:
    inputs:
      org:
        description: 'Which "Revanced" do you want to patch?'
        required: true
        default: 'Revanced'
        type: choice
        options:
          - 'Revanced Extended'
          - 'Revanced Extended Beta'
  workflow_call:
    inputs:
      org:
        required: true
        type: string
jobs:
  patch_rve:
    name: Patch Revanced Extended Stable
    if: ${{ github.event.inputs.org == 'Revanced Extended' || inputs.org == 'Revanced Extended' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve
        if: steps.check-gh-rve.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_rve
          path: |
            ./release/*.apk
  release_rve:
    name: Release Revanced Extended Stable
    needs: patch_rve
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_rve
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release
  patch_rve_beta:
    name: Patch Revanced Extended Beta
    if: ${{ github.event.inputs.org == 'Revanced Extended Beta' || inputs.org == 'Revanced Extended Beta' }}
    runs-on: ubuntu-latest
    container:
      image: ubuntu:20.04
      options: --user root
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.2
      - name: Preparing to patch
        uses: ./.github/actions/preparing
      - name: Install library
        run: |
          apt-get update
          apt-get install -y curl jq wget unzip
      - name: Check github connection
        id: check-gh-rve-beta
        run: bash src/etc/connection.sh
      - name: Patch apk
        id: patch-rve-beta
        if: steps.check-gh-rve-beta.outputs.internet_error == '0'
        run: bash src/build/Revanced-Extended-Beta.sh
      - name: Cache
        uses: actions/upload-artifact@v4
        with:
          name: Cache_rve_beta
          path: |
            ./release/*.apk
  release_rve_beta:
    name: Release Revanced Extended Beta
    needs: patch_rve_beta
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache
        uses: actions/download-artifact@v4
        with:
          name: Cache_rve_beta
          path: ./release
      - name: Releasing APK files
        uses: ./.github/actions/release
